{{- if .Values.ingress.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "python-app.fullname" . }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Values.ingress.host | quote }}
    port:
      name: http
      number: 80
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "python-app.fullname" . }}
spec:
  hosts:
  - {{ .Values.ingress.host | quote }}
  gateways:
  - {{ include "python-app.fullname" . }}
  http:
  - route:
    - destination:
        host: {{ include "python-app.fullname" . }}
        port:
          number: {{ .Values.service.port }}
{{- end }}
