apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: oba11/nginx-proxy-etcd:latest
          args: ["-node=172.17.4.51:2379"]
          ports:
            - containerPort: 80
              hostPort: 80
