apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: python-app
  name: python-app
spec:
  replicas: 1
  selector:
    name: python-app
  template:
    metadata:
      labels:
        name: python-app
    spec:
      containers:
          name: python-app
          image: oba11/python-app:latest
          ports:
            - containerPort: 8080
