[template]
src   = "default.conf.tmpl"
dest  = "/etc/nginx/conf.d/default.conf"
owner = "root"
group = "root"
mode  = "0644"
keys = [
  "/registry/services/specs"
]
check_cmd  = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "/usr/sbin/nginx -s reload"
