name: Docker Image CI

on:
  push:
    branches:
      - master
    paths:
      - 'python-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      run: docker login docker.pkg.github.com -u oba11 -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Build
      run: docker build --tag docker.pkg.github.com/oba11/hm-demo/60b15dd1:latest .
      working-directory: ./python-app
    - name: Docker Publish
      run: docker push docker.pkg.github.com/oba11/hm-demo/60b15dd1:latest
